apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: x4mvgwk1v-nodejs 
  janus-idp.io/tekton: x4mvgwk1v-nodejs
  backstage.io/kubernetes-id: x4mvgwk1v-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x4mvgwk1v-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml