apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x4mvgwk1v-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x4mvgwk1v-nodejs 
  name: x4mvgwk1v-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: x4mvgwk1v-nodejs 
